version: 2

project_name: aws-mfa-go

before:
  hooks:
    - go mod tidy

builds:
  - id: aws-mfa-go
    main: ./cmd/aws-mfa-go
    binary: aws-mfa-go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    ids:
      - aws-mfa-go
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true

homebrew_casks:
  - name: aws-mfa-go
    ids:
      - default
    binaries:
      - aws-mfa-go
    homepage: "https://github.com/jlis/aws-mfa-go"
    description: "Minimal AWS MFA helper for the CLI (STS GetSessionToken -> ~/.aws/credentials)"
    url:
      verified: github.com/jlis/aws-mfa-go
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-mfa-go"]
          end
    repository:
      owner: jlis
      name: homebrew-tap
      branch: master
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: "goreleaserbot"
      email: "goreleaserbot@users.noreply.github.com"

