package credentials

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestStore_WritesExplicitDefaultSectionHeader(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "credentials")

	s, err := Load(path)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}

	s.Set("default-long-term", "aws_access_key_id", "AKIA_TEST")
	s.Set("default-long-term", "aws_secret_access_key", "SECRET_TEST")
	s.Set("default", "aws_access_key_id", "ASIA_TEST")

	if err := s.SaveAtomic(); err != nil {
		t.Fatalf("SaveAtomic: %v", err)
	}

	raw, err := os.ReadFile(path) //nolint:gosec // G304: path is generated by t.TempDir()
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}

	contents := string(raw)
	if !strings.Contains(contents, "[default]") {
		t.Fatalf("expected credentials file to contain [default] section header, got:\n%s", contents)
	}
	if strings.Contains(contents, "ASIA_TEST") && !strings.Contains(contents, "[default]") {
		t.Fatalf("short-term credentials appear written without a [default] header:\n%s", contents)
	}
}
